version: "3.9"
services:
  mongo_db:
    container_name: db_container
    image: mongo
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      mongoURI: mongodb://mongo_db:27017/itdb
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
